name: Phyaddr Snyk Container Scanning

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  snyk:
    name: Build and Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
      - uses: actions/checkout@v3
      
      - name: Build Docker Image
        run: docker build . -t phyaddr

      - name: Run Snyk to check image for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: phyaddr
          args: --file=Dockerfile
          
      - name: Report To GitHub Code Scanning
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
